Fix submitting problems with Non-ASCII characters
openedx/xqueue pull request #127
Opened 2017-11-25 02:46 UTC by liukangxu

LMS shows “Unable to deliver your submission to grader (Reason: unexpected HTTP status code [500]). Please try again later” when filename contains Non-ASCII characters.

2017-11-25 02:46 UTC, edx-webhook commented
Thanks for the pull request, @liukangxu! I've created [OSPR-2023](https://openedx.atlassian.net/browse/OSPR-2023) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/xqueue/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2017-11-27 18:19 UTC, nedbat commented
@liukangxu Thanks for this fix! We really appreciate the help. 

Please sign and send in your contributor agreement so that I can get this merged.  Thanks

2017-11-28 13:55 UTC, liukangxu commented
@nedbat I have already signed and send in my contributor agreement to legal@edx.org, but I haven't received any reply so far. So I should just wait or do something else?

2017-11-28 15:57 UTC, nedbat commented
@liukangxu We've received your agreement, thanks! Welcome to the community.

2017-11-28 16:00 UTC, nedbat commented
@liukangxu Would it be possible to add a test for this case?  It would be great to ensure it stays working in the future.

2017-11-29 08:01 UTC, liukangxu commented
Just added one test case with Chinese character filename. It seems to be working fine.

2017-11-29 20:55 UTC, nedbat requested changes

2017-11-29 20:55 UTC, nedbat commented on queue/tests/test_lms_interface.py
> +        self.assertIn(key, files)
Thanks for the test.  This duplicates seven lines from just above.  Can we put the args to ContentFile into a list, and then loop over them to try the different file names?

2017-11-30 06:30 UTC, liukangxu commented on queue/tests/test_lms_interface.py
> +        self.assertIn(key, files)
Thanks for your advice, how about the updated version?

2017-12-08 14:19 UTC, liukangxu commented
@nedbat Any further suggestions?

2017-12-11 22:18 UTC, nedbat commented
@liukangxu Hi, sorry for the delay.  I don't understand this repo well, so I tried an experiment: I changed the file name in the test to Chinese, without your fix, and ran the tests.  They all passed.  I see the string 'upload' being passed to make_hashkey.  Are you certain that this fix fixes a problem you are having?  Do you have the full error reports for the 500 error that happens?

2018-07-20 15:47 UTC, mduboseedx commented
@liukangxu Are you still pursuing this PR? If not, I'll close it, but feel free to reopen it in the future.

2018-07-31 17:35 UTC, mduboseedx commented
@liukangxu I'll close this PR for now, but feel free to reopen

2018-07-31 17:35 UTC, closed without merging

2018-07-31 17:35 UTC, edx-webhook commented
@liukangxu Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/127&entry.1484655318=https://github.com/liukangxu&entry.752974735=2017-11-25+02:46&entry.1917517419=2018-07-31+17:35&entry.2133058324=No) so we can improve your experience in the future.