Close AMQP channel prior to closing connection in producer
openedx/xqueue pull request #131
Opened 2018-01-08 09:42 UTC by kaizoku

We were seeing many client disconnects on our RabbitMQ server with the warning `client unexpectedly closed TCP connection`.
This was traced back to xqueue closing the TCP connection before the AMQP channels were closed.
This patch introduces a call to channel.close() to prevent this warning.

2018-01-10 15:26 UTC, edx-webhook commented
Thanks for the pull request, @kaizoku! I've created [OSPR-2060](https://openedx.atlassian.net/browse/OSPR-2060) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/xqueue/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2018-01-10 21:33 UTC, nedbat requested changes

2018-01-10 21:33 UTC, nedbat commented on queue/producer.py
> +    channel.close()
Good catch.  I wonder if a with-statement would be a better way to handle this to ensure it's definitely cleaned up properly?  Even if these objects don't support the context manager protocol, we could use:
```
with contextlib.closing(channel):
    queue = channel.queue_etc etc
```
(we could do that for `connection` too...)

2018-01-15 00:42 UTC, kaizoku commented on queue/producer.py
> +    channel.close()
Ah yes, context managers are real handy. I've updated this to use with statements and contextlib.closing(), since the [version of pika used in xqueue doesn't have `__enter__` or `__exit__`](https://github.com/pika/pika/blob/a731347fc07812401201e9415141059ebfb86c4a/pika/adapters/base_connection.py#L148).
On master however, pika does support context managers for both [the BlockingConnection class](https://github.com/pika/pika/blob/66387744cf971ebb1c69cf48b7de017f40ff9bbe/pika/adapters/blocking_connection.py#L766), and [the BlockingChannel class](https://github.com/pika/pika/blob/66387744cf971ebb1c69cf48b7de017f40ff9bbe/pika/adapters/blocking_connection.py#L1178).

2018-01-22 21:38 UTC, nedbat approved these changes

2018-01-22 21:39 UTC, merged

2018-01-22 21:39 UTC, edx-webhook commented
@kaizoku 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/131&entry.1484655318=https://github.com/kaizoku&entry.752974735=2018-01-08+09:42&entry.1917517419=2018-01-22+21:39&entry.2133058324=Yes) so we can improve your experience in the future.