Rename djangoapp app
openedx/xqueue pull request #575
Opened 2019-10-02 12:52 UTC by zainab-amir

"queue" app name conflicts with a module of urllib3 which is installed as a dependency for requests package.

- I have changed the django app name by keeping the original db name using db_table field in model meta. 
- Updated references to old app name in settings, makefile, coverage file
- Updated imports
- Updated tests to mock correct app functionality

PROD-389

2019-10-02 13:34 UTC, feanil requested changes
Generally looks good, I would suggest changing the name of the new package to 'submission_queue' instead of `submit_queue` but once that's done I think this should be good to go.

2019-10-03 14:43 UTC, feanil approved these changes

2019-10-03 14:43 UTC, feanil commented
@zainab-amir changes look good but let's hold off on merging until we have documented a full deployment plan.

2019-10-31 17:28 UTC, merged

2019-10-31 17:28 UTC, coryleeio commented
Migrations are faked so i've merged this. I have a runbook in the associated ops ticket