WIP [BD-6] Update tests to run using python 3.8.
openedx/xqueue pull request #743
Opened 2020-05-16 22:15 UTC by ericfab179

2020-05-16 22:16 UTC, edx-webhook commented
Thanks for the pull request, @ericfab179! I've created [OSPR-4546](https://openedx.atlassian.net/browse/OSPR-4546) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2020-05-18 09:10 UTC, UsamaSadiq requested changes

2020-05-18 09:10 UTC, UsamaSadiq commented on .travis.yml
> +  include:
You can keep the `env` section and just exclude python3.8 quality from the matrix. Then you won't need to include each env independently.

2020-05-18 09:28 UTC, mzulqarnain1 approved these changes

2020-05-18 13:56 UTC, mraarif commented on .travis.yml
> +  include:
+1

2020-05-18 14:07 UTC, morenol commented on .travis.yml
> +  include:
The thing is that the other TOXENVs are `py35-django22` and `py38-django22` and I would have to exclude thee.

Do you have any idea of how to solve that?

2020-05-18 14:44 UTC, mraarif commented on .travis.yml
> +  include:
```
python:
- 3.5
- 3.8

env:
- TOXENV=django22
- TOXENV=quality

matrix:
    exclude:
        - python: 3.8
           env:
                - TOXENV=py38-quality
```

something like this

2020-05-18 15:19 UTC, morenol commented on .travis.yml
> +  include:
But I mean, if I use TOXENV=django22 in both python 3.5 and python3.8 will be used python3.5, because all these tasks run inside a docker container that has python3.5 as default python.

2020-05-18 16:42 UTC, UsamaSadiq commented on .travis.yml
> +  include:
That won't be a problem because Tox will use the different python version for running test separately. You can test by adding a new commit. Hopefully it'll work as expected and there won't be an issue.

2020-05-19 00:14 UTC, edx-webhook commented
@ericfab179 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/743&entry.1484655318=https://github.com/ericfab179&entry.752974735=2020-05-16+22:15&entry.1917517419=2020-05-19+00:14&entry.2133058324=No) so we can improve your experience in the future.

2020-05-19 00:14 UTC, edx-webhook commented
Hello @ericfab179: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

2020-05-19 00:14 UTC, closed without merging

2020-05-19 00:15 UTC, edx-webhook commented
@ericfab179 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xqueue&entry.867055334=https://github.com/edx/xqueue/pull/743&entry.1484655318=https://github.com/ericfab179&entry.752974735=2020-05-16+22:15&entry.1917517419=2020-05-19+00:14&entry.2133058324=No) so we can improve your experience in the future.

2020-05-19 00:23 UTC, ericfab179 commented
@mzulqarnain1 @UsamaSadiq @mraarif @awais786 I created a new PR since I tried to close and re-open this PR to force tests to run (they were blocked) and the bot does not allow me to re open it again. 
New PR: https://github.com/edx/xqueue/pull/744