Convert ansible to dockerfile
openedx/xqueue pull request #863
Opened 2022-09-09 09:20 UTC by mumarkhan999

TBD

2023-02-14 23:13 UTC, iamsobanjaved requested changes
Added a few comments and suggestions

2023-02-14 23:13 UTC, iamsobanjaved commented on Dockerfile
> +rm -rf /var/lib/apt/lists/*
Append all subsequent lines in `RUN` command

2023-02-14 23:13 UTC, iamsobanjaved commented on Dockerfile
> +
nit: extra empty line can be removed

2023-02-14 23:13 UTC, iamsobanjaved commented on Dockerfile
> +COPY requirements.txt ${XQUEUE_APP_DIR}/requirements.txt
is this `XQUEUE_APP_DIR` instead of `XQUEUE_CODE_DIR` by mistake?

2023-02-14 23:13 UTC, iamsobanjaved commented on Dockerfile
> +COPY /manage.py /edx/bin/manage.xqueue
Why do we need this step?

2023-02-14 23:13 UTC, iamsobanjaved commented on Dockerfile
> +
Too many extra lines

2023-03-01 12:28 UTC, zubairshakoorarbisoft commented on Dockerfile
> +
extra lines removed

2023-03-01 12:28 UTC, zubairshakoorarbisoft commented on Dockerfile
> +COPY /manage.py /edx/bin/manage.xqueue
I am not sure about this but I could verify its usage/reference in the whole project

2023-03-01 12:28 UTC, zubairshakoorarbisoft commented on Dockerfile
> +COPY requirements.txt ${XQUEUE_APP_DIR}/requirements.txt
I think umar is copying requirements folder in the Code Directory and requirements.txt in the app root directory

2023-03-01 12:28 UTC, zubairshakoorarbisoft commented on Dockerfile
> +
removed

2023-03-01 12:28 UTC, zubairshakoorarbisoft commented on Dockerfile
> +rm -rf /var/lib/apt/lists/*
added indents

2023-03-02 08:27 UTC, zubairshakoorarbisoft commented on Dockerfile
> +COPY /manage.py /edx/bin/manage.xqueue
@iamsobanjaved  we can remove this line, it was using in ansible since wee are not using it so we can remove it. I just confirmed it from AHT

2023-04-11 20:56 UTC, iamsobanjaved approved these changes

2023-04-27 15:55 UTC, leangseu-edx approved these changes
LGTM 👍

2023-04-28 18:37 UTC, merged